#SPDX-License-Identifier: MIT-0
---
# Базовые пользователи, общие для всех нод/проектов (если есть)
cluster_users_common: [] # Далее - см. group_vars
# Переменная существует всегда;
# У неё есть безопасное значение по умолчанию;
# Её можно переопределить в inventory, group_vars, host_vars, extra_vars и т.д.

# Пользователи, специфичные для конкретного проекта / окружения
#cluster_users_project: []