cluster_users_common:
  - name: ansible
    comment: "Configuration management user"
    uid: 1100
    gid: 1100
    group: ansible
    groups:
      - wheel
    home: /home/ansible
    shell: /bin/bash
    ssh_keys:
      - "{{ vault_ansible_ssh_pubkey }}"
    sudo:
      - "ALL=(ALL) NOPASSWD:ALL" # Разрешить пользователю выполнять любые команды от любого пользователя (ALL=ALL) без запроса пароля через sudo
    lock_password: true