$ANSIBLE_VAULT;1.1;AES256
64303336313166386265666237343663333337313161623636653664383964623639323235386364
3137346337396438323732346464326464353562366537660a373066323331353630663439363133
63333865306637356235376438616135646337363631393264363965356532636564626265666564
3437323231383539360a306564316135333662623630353365616436346166653264393334643566
35336234613138646566663463626231393435663861643939646330313431333431663963343932
62356561386236656462323936383530363165383435343032656533346533366330343537653639
33353364303466666535356639613532613534323035353037393565653063343331333466636439
33633930386161313861353432623838663435393165653836333164663032613061316566666138
38383133653635313637356236613435366564646464313031353634303736313565383239336466
6635653135646439396234353334656266306435633036353731
